import Head from "next/head";
import Image from "next/image";
import "tailwindcss/tailwind.css";
import Home from "./home";

export default function Index() {
  return (
    <div className="">
      <Head>
        <title>Feane Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <Home />
    </div>
  );
}
