import Head from "next/head";
import Image from "next/image";
import "tailwindcss/tailwind.css";
import Home from "./home";
import Header from "./components/layout/Header";
import Input from "./components/form/Input";

export default function Index() {
  return (
    <>
      <div className="">
        <Head>
          <title>Feane Restaurant</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/favicon.png" />
        </Head>
        <Header />
        <Home />
        <div className="p-20 container mx-auto">
          <Input />
        </div>
      </div>
    </>
  );
}
